### ISSUE TITLE
Can't change weekend off time from 8PM

### ISSUE THREAD

**Issue by augustf** [concerto/concerto-hardware#29]
Odd as it may seem, I'm unable to change my screen weekend off time away from 8PM. I set the control for weekend on at 1PM and off at 3PM, but the off value remains 8PM. I'm able to change the weekday on and off times without incident.

**Comment by zr2d2** [comment]
That is GMT-4, or EDT. Maybe it isn't being saved to the database

**Comment by augustf** [comment]
An excellent observation; it hadn't occurred to me what meaning 8PM would have here.

**Comment by mikldt** [comment]
Unable to reproduce. Can you provide more details?

**Comment by augustf** [comment]
I just bashed on my local install a bit and am now unable to replicate this. When I filed it (and as Zach pointed out), the weekend off time was going to UTC. If no one else can reproduce this, let's close it out.

**Comment by augustf** [comment]
Looking back on the code, it could have arisen from this line in the form partial:

```
 f.text_field(:wknd_off_time, :maxlength => 20, :class => "timefield input-small", :value => @player.fmt_time(@player.wknd_off_time, "%l:%M%P") || ConcertoConfig[:content_default_end_time]) ```
This invokes the default content end time, which assuming our timezone stuff is being silly, is 8PM eastern.
